### ISSUE TITLE
Replacing UITextField with UITextView and adaptive height

### ISSUE THREAD

**Issue by DazChong** [cokaholic/TKKeyboardControl#1]
Hi, I tried to replace the UITextField with UITextView to support adaptive height with max of 5 lines, but experiencing the UITextView scrollView keep scrolling whenever editing begin. Do you know how to overcome the issue?

**Comment by cztatsumi-keisuke** [comment]
The experience happens from the time UITextField begin editing.
When UITextField do NOT begin editing, can't it.
